In [6]:
import pandas as pd

import preprocess as preproc
import util as utility
import model as md

In [7]:
train_data = pd.read_csv('data store/training_dataset.csv')
print(train_data.shape)
train_data.head()

(92770, 16)

,Unnamed: 0,Data Year - Fiscal,Tobin's Q,EPS,Liquidity,Profitability,Productivity,Leverage Ratio,Asset Turnover,Operational Margin,Return on Equity,Market Book Ratio,Assets Growth,Sales Growth,Employee Growth,BK
0,28077,2001,1.09,-0.06,0.35,-0.44,-0.03,0.16,1.59,-0.02,-0.05,16.64,-0.065525,0.009159,0.478261,0
1,49401,1994,6.32,0.88,0.63,0.27,0.25,0.00,5.30,0.05,0.03,116.38,1.273175,0.525437,0.578947,0
2,25363,1987,0.69,0.27,0.53,0.63,0.03,0.13,1.54,0.02,0.10,1.16,-0.070146,-0.040578,-0.114428,0
3,33446,2003,NaN,-0.90,NaN,NaN,NaN,0.00,NaN,NaN,-1.50,-13.87,-1.000000,-1.000000,-0.997512,0
4,6168,1987,0.94,0.45,0.50,0.34,0.06,0.14,0.91,0.06,0.08,4.56,-0.009882,0.057643,-0.292929,0

In [8]:
eval_data = pd.read_csv('data store/evaluation_dataset.csv')
print(eval_data.shape)

(100, 16)

In [9]:
#  Prepare preprocessor 
#  Go through data transformation process and generate processed dataframe

features_dropna = ["Tobin's Q", "EPS", "Leverage Ratio", "Return on Equity", "Market Book Ratio", "Operational Margin", "Assets Growth", "Productivity", "Sales Growth", "Employee Growth"]
features_impute = ["Liquidity", "Profitability", "Asset Turnover"]
features_todrop = ["Unnamed: 0", "Liquidity"]
target = "BK"
train_data_object = preproc.preprocessor(train_data)
eval_data_object = preproc.preprocessor(eval_data)

processed_df = preproc.feature_preprocessor(train_data_object, features_dropna, features_impute, features_todrop, target)
processed_eval_df = preproc.feature_preprocessor(eval_data_object, features_dropna, features_impute, features_todrop, target)

before processing:  (92770, 16)
after processing:  (81113, 14)
before processing:  (100, 16)
after processing:  (90, 14)

In [10]:
processed_df = preproc.clean_column_name(processed_df)
processed_eval_df =  preproc.clean_column_name(processed_eval_df)

# write to csv
processed_df.to_csv("data store/training_dataset_processed.csv", encoding='utf-8', index=False)
processed_eval_df.to_csv("data store/evaluation_dataset_processed.csv", encoding='utf-8', index=False)

processed_df.to_csv("data store/training_dataset_processed_tf.csv", encoding='utf-8', index=False, header=False)
processed_eval_df.to_csv("data store/evaluation_dataset_processed_tf.csv", encoding='utf-8', index=False, header=False)

processed_df.head()

,Fiscal_year,Tobin_Q,EPS,Profitability,Productivity,Leverage_Ratio,Asset_Turnover,Operational_Margin,Return_Equity,Market_Book_Ratio,Assets_Growth,Sales_Growth,Employee_Growth,BK
0,-0.328589,-0.033365,0.006825,0.032684,0.033879,-0.004972,0.209890,0.034980,0.007617,-0.028198,-0.016158,-0.010898,0.009170,0
1,-1.051756,0.007623,0.007226,0.035314,0.073895,-0.005563,1.882852,0.035305,0.007847,-0.021270,0.004767,-0.008078,0.016147,0
2,-1.774924,-0.036499,0.006966,0.036647,0.042454,-0.005083,0.187343,0.035166,0.008048,-0.029274,-0.016230,-0.011170,-0.031906,0
4,-1.774924,-0.034540,0.007042,0.035573,0.046741,-0.005046,-0.096745,0.035352,0.007990,-0.029037,-0.015288,-0.010633,-0.044277,0
5,-0.638518,-0.029995,0.007802,0.035129,0.051029,-0.002829,0.110685,0.035398,0.007904,-0.026824,-0.013561,-0.010451,-0.013985,0