In [2]:
import pandas as pd

from helper import preprocess as preproc
from helper import util
from helper import ml_model as md

In [3]:
train_data = pd.read_csv('data store/training_dataset.csv')
print(train_data.shape)
train_data.head()

(92770, 16)

,Unnamed: 0,Data Year - Fiscal,Tobin's Q,EPS,Liquidity,Profitability,Productivity,Leverage Ratio,Asset Turnover,Operational Margin,Return on Equity,Market Book Ratio,Assets Growth,Sales Growth,Employee Growth,BK
0,84623,2010,7.01,-1.63,0.39,-1.07,-0.38,0.35,0.30,-1.26,-0.06,1158.51,NaN,NaN,NaN,0
1,47517,2015,3.96,-0.02,0.05,-74.50,-0.88,0.00,0.00,NaN,-0.22,35.64,0.000000,0.000000,-1.000000,0
2,24972,2012,1.75,3.61,0.28,0.39,0.13,0.38,1.83,0.07,0.07,56.13,0.093617,-0.021353,0.038961,0
3,73742,2006,2.26,1.52,0.27,0.32,0.15,0.00,1.85,0.08,0.04,89.74,0.103001,0.160042,-0.066667,0
4,28721,1995,1.34,1.68,0.34,-0.22,-0.07,0.04,0.04,-1.80,0.17,5.59,-0.341677,-0.897905,3.603604,0

In [4]:
eval_data = pd.read_csv('data store/evaluation_dataset.csv')
print(eval_data.shape)

(100, 16)

In [5]:
#  Prepare preprocessor 
#  Go through data transformation process and generate processed dataframe

features_dropna = ["Tobin's Q", "EPS", "Leverage Ratio", "Return on Equity", "Market Book Ratio", "Operational Margin", "Assets Growth", "Productivity", "Sales Growth", "Employee Growth"]
features_impute = ["Liquidity", "Profitability", "Asset Turnover"]
features_todrop = ["Unnamed: 0", "Liquidity"]
target = "BK"
train_data_object = preproc.preprocessor(train_data)
eval_data_object = preproc.preprocessor(eval_data)

processed_df = preproc.feature_preprocessor(train_data_object, features_dropna, features_impute, features_todrop, target)
processed_eval_df = preproc.feature_preprocessor(eval_data_object, features_dropna, features_impute, features_todrop, target)

before processing:  (92770, 16)
after processing:  (81116, 14)
before processing:  (100, 16)
after processing:  (86, 14)

In [6]:
processed_df = preproc.clean_column_name(processed_df)
processed_eval_df =  preproc.clean_column_name(processed_eval_df)

# write to csv
processed_df.to_csv("data store/training_dataset_processed.csv", encoding='utf-8', index=False)
processed_eval_df.to_csv("data store/evaluation_dataset_processed.csv", encoding='utf-8', index=False)

processed_df.to_csv("data store/training_dataset_processed_tf.csv", encoding='utf-8', index=False, header=False)
processed_eval_df.to_csv("data store/evaluation_dataset_processed_tf.csv", encoding='utf-8', index=False, header=False)

processed_df.head()

,Fiscal_year,Tobin_Q,EPS,Profitability,Productivity,Leverage_Ratio,Asset_Turnover,Operational_Margin,Return_Equity,Market_Book_Ratio,Assets_Growth,Sales_Growth,Employee_Growth,BK
2,0.807696,-0.028185,0.008396,0.035748,0.056709,-0.004178,0.318236,0.035390,0.007977,-0.025455,-0.013670,-0.011087,-0.021262,0
3,0.187838,-0.024188,0.007504,0.035489,0.059567,-0.005582,0.327255,0.035437,0.007891,-0.023121,-0.013524,-0.010096,-0.028584,0
4,-0.948570,-0.031399,0.007572,0.033488,0.028125,-0.005434,-0.488981,0.026702,0.008264,-0.028966,-0.020475,-0.015875,0.225821,0
5,1.324245,-0.037120,0.006839,0.025042,0.018121,-0.005582,-0.461923,0.028328,0.007174,-0.025334,-0.016555,-0.003538,-0.016261,0
6,0.911006,-0.027402,0.007547,0.034674,0.059567,0.003359,-0.159781,0.035948,0.007977,1.275113,-0.014960,-0.010949,-0.017650,0